language: node_js
node_js:
  - "6"
  - "5"
after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/codeclimate-test-reporter'
notifications:
  email: false
  slack: noop-fa:zbwZeeSi5kgDshj6FO4BkNZU

